### ISSUE TITLE
UI is messed up

### ISSUE THREAD

**Issue by DJCrashdummy** [nextcloud/tasks#58]
### Steps to reproduce
unfortunately i'm not sure right now _(please be patient, these are my first steps on github!)_

### Expected behaviour
a clean an functional UI

### Actual behaviour
have a look at the screenshot... ![aufgaben - testcloud - 2017-03-01](https://cloud.githubusercontent.com/assets/26110463/23456818/4f70cc4e-fe75-11e6-8c65-6dff1c40bc65.png)
 the UI is definitely not like it should be.

### Server configuration
i'm using a hoster, so i can't tell you everything exactly...

**Operating system**: Linux 3.13.0-110-generic #157-Ubuntu SMP x86_64

**Web server:** Apache 2.0

**Database:** mysql 5.6.33

**PHP version:** 7.0.14

**Nextcloud version:** 11.0.2.7

**Tasks version:** 0.9.4

**Updated from an older Nextcloud or fresh install:** updated from 11.0.1.2 with the app

**Signing status:**

```
Integrity checker has been disabled. Integrity cannot be verified.
```
i think this is because i tried to "sideload" the checksum-app via FTP because it can't be downloaded via the apps-menu _(Client error response [url] https://herzberg-digital.de/checksum.tar.gz [status code] 404 [reason phrase] Not Found)_... then it showed an app-update immediately and after applying that i got an integrity-warning on the admin-page.

**List of activated apps:**
i use this as a testing-instance so it is sadly a huge list. - at least i'm pretty sure the problems in the main-window are related with JavaScript XMPP Chat.
```
Activity 2.4.1
Collaborative tags 1.1.3
Comments 1.1.0
Default encryption module 1.4.1
Deleted files 1.1.0
External storage support 1.1.2
External user support 0.4
Federation 1.1.1
File access control 1.1.2
File sharing 1.1.1
First run wizard 2.0
Gallery 16.0.0
Log Reader 2.0.0
Mail template editor 0.2
Nextcloud announcements 1.0
Notifications 1.0.1
Password policy 1.1.0
PDF viewer 1.0.1
Retention 1.0.1
Server info 1.1.1
Share by mail 1.0.1
Text editor 2.2
Theming 1.1.1
Update notification 1.1.1
Usage survey 0.1.5
Versions 1.4.0
Video player 1.0.0
Activities for shared file downloads 1.0.0
Activity Log 0.0.1
Admin notifications 1.0.0
Announcement Center 3.0.0
AppOrder 0.3.3
Calendar 1.5.0
Contacts 1.5.3
JavaScript XMPP Chat 3.1.1
Keeweb 0.3.0
Mail 0.6.2
News 10.1.0
Notizen 2.2.0
Phone Sync 1.11.5
RainLoop 4.26.1
Reader (ebook reader) 0.8.4
Tasks 0.9.4
Video calls 1.2.0
```

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => 'XXX',
  'passwordsalt' => 'XXX',
  'secret' => 'XXX',
  'trusted_domains' => 
  array (
    0 => 'test.domain.tld',
  ),
  'datadirectory' => '/www/htdocs/XXX/test/nextcloud/data',
  'overwrite.cli.url' => 'http://test.domain.tld/nextcloud',
  'dbtype' => 'mysql',
  'version' => '11.0.2.7',
  'dbname' => 'XXX',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'XXX_',
  'dbuser' => 'XXX',
  'dbpassword' => 'XXX',
  'logtimezone' => 'Europe/Berlin',
  'installed' => true,
  'default_language' => 'de',
  'memcache.local' => '\\OC\\Memcache\\ArrayCache',
  'tempdirectory' => '/www/htdocs/XXX/test/nextcloud/tmp/',
  'updater.release.channel' => 'production',
  'loglevel' => 0,
  'theme' => '',
  'updater.secret' => 'XXX',
  'maintenance' => false,
);
```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** yes, just in case for external storage.

**Are you using an external user-backend, if yes which one:** no

#### Browser
i'm using Firefox 51.0.1 (64-Bit)

**Comment by raimund-schluessler** [comment]
Thanks for the report. This should be fixed in https://github.com/nextcloud/tasks/pull/53. I didn't release it to the appstore yet, since I thought the changes would only be necessary for NC12 which is not released yet. However, they seem to have backported the changes to NC 11.0.2. I will release a fixed version on the appstore as soon as possible.

**Comment by DJCrashdummy** [comment]
i'm not 100% sure now, but i think that these issues also show up before updating (under 11.0.1.2)...

**Comment by raimund-schluessler** [comment]
At least for me it looked good on 11.0.1, but is broken with 11.0.2 now. You could check if the issue is gone by installing the latest master from github.

**Comment by DJCrashdummy** [comment]
you are (at least partly) right. with the tasks-master the menu is fine.

but the issues in the main window still persist exactly as on the screenshot (they were also present on NC 11.0.1.2) and are definitely related with JavaScript XMPP Chat (ojsxc).

but i'm also afraid it is not (only) on their behalf to fix...
- i have never ever created a task on this instance but the editing-window on the right side is open all the time
- it has no title (and therefore the gray bar ends somewhere)
- at the bottom there is no trashbin-icon (well... there isn't anything i could delete)
- although the arrow/close-icon is there, the editing-window won't close and so i can't ever access the sorting-icon on the top right!

**Comment by raimund-schluessler** [comment]
> definitely related with JavaScript XMPP Chat (ojsxc).

What happens when you deactivate this app? Do the issues disappear?

> - although the arrow/close-icon is there, the editing-window won't close
> - and the worst is that the editing-window overlaps the main-window, and so i can't ever access the sorting-icon on the top right!

It sounds like something is overwriting the css rules for the detail window. It could be something similar to https://github.com/nextcloud/tasks/issues/33 and might be solved once https://github.com/nextcloud/tasks/issues/35 is closed but we need to know what causes it exactly.

> - it has no title (and therefore the gray bar ends somewhere)
> - at the bottom there is no trashbin-icon (well... there isn't anything i could delete)

This is normal. The title is only shown if there is a task, the trashbin icon only shows up if it is writable.

**Comment by DJCrashdummy** [comment]
ok... now i played a little bit around and found something interesting:
although the arrow/close-icon does not react, if i click somewhere (with no function) into the editing-window/frame the frame stays where it is, **but** it just tells me _"Aufgabe nicht gefunden!"_/_"Task not found!"_ **and** the sorting-icon moves left, right beside the editing-window/frame like it usual is.
![aufgaben - testcloud - 2017-03-01](https://cloud.githubusercontent.com/assets/26110463/23460964/18de5a4e-fe88-11e6-86ae-a8addd7ed3d0.png)


**BUT** at the moment i try to click the icon or anywhere else, the icon hides immediately under the editing-window/frame again!
clicking into the editing-window/frame (_"Aufgabe nicht gefunden!"_/_"Task not found!"_ stays there) shows the icon again and so on...

also the URL changes every time from .../apps/tasks/#/collections/all (icon hidden) to .../apps/tasks/#/collections/all/tasks/undefined (icon showed).


by the way: as far as i can tell the status of the ojsxc-window/frame has no influence. - i think more and more this is a tasks-issue and not a ojsxc-issue. :-/

**Comment by raimund-schluessler** [comment]
As I said, something is overwriting the css rules for the appsidebar. Hence, the appsidebar does not move, as it is always shown.

Please try do *disable* the JavaScript XMPP Chat 3.1.1 app in the app management and have a look again.

**Comment by DJCrashdummy** [comment]
sorry, i just saw your reply after my post...

> > definitely related with JavaScript XMPP Chat (ojsxc).
> 
> What happens when you deactivate this app? Do the issues disappear?

that i wanted to tell with _definitively related_... when ojsxc is deactivated the tasks-UI looks like it should.

> It sounds like something is overwriting the css rules for the detail window. It could be something similar to #33 and might be solved once #35 is closed but we need to know what causes it exactly.

well... i'm sadly not a developer so i can't go deeper in details, but it sounds related...


_by the way: completely unrelated and not really an issue, but i just noticed it... as you can see in the second screenshot (with the tasks-master from today) the text in the gray bar to create a new task is stuck to the bottom._

**Comment by raimund-schluessler** [comment]
> that i wanted to tell with definitively related... when ojsxc is deactivated the tasks-UI looks like it should.

Ok, thanks for letting me know. Then I can have a look why it is messing things up. I will probably provide a fix this evening.

> well... i'm sadly not a developer so i can't go deeper in details, but it sounds related...

No problem. To know that ojsxc interferes with Tasks should be enough to solve the issue.

> by the way: completely unrelated and not really an issue, but i just noticed it... as you can see in the second screenshot (with the tasks-master from today) the text in the gray bar to create a new task is stuck to the bottom.

Yes, I noticed that too. This does not occur on NC12 for which I had to fix the Tasks app, but obviously this rule was not backported to NC 11.0.2.

**Comment by raimund-schluessler** [comment]
Please have a look at #59.

**Comment by DJCrashdummy** [comment]
i have to say: you are AWESOME!

i was not sure about joining github and opening an issue: is it worth the time/work, will it get fixed (because ojsxc is marked as nightly/Unstable) or not even noticed...?

i just had the the hope it get fixed sometime in the future, but i didn't dare to dream of a fix within one day! i'm blown away...
thank you very much!!!

**Comment by raimund-schluessler** [comment]
Glad everything is fixed now. But don't get used to this, I don't always have freetime to fix stuff 😉 

I also pushed a new version to the appstore, so everyone who updated to 11.0.2 can update the Tasks app conveniently.
